---
# for now we'll just lean on QEMU via Docker BuildX to create multi-arch
# images, since we don't have arm64 rigs in the CI farm (er... rather, GitHub
# doesn't, and we don't have custom in-house runners) to build on.
#
# one day, whether it's on GH Actions or a custom CI system, the ideal (read:
# often 3-6x faster for crunch-heavy loads like compiling C++ stuff, like
# Watchman) world would be to build images on their native arch, push to an
# intermediate tag, then combine them into a manifest manually with a process
# like
# http://web.archive.org/web/20220303000513/https://piers.rocks/docker/containers/manifests/2018/11/02/using-docker-manifests-for-multiple-archs.html

name: docker-build

on:
  push:
    tags:
      - '*'

jobs:
  sorbet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required because we do tag detection for versioning
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build Images
        run: make PUSH=1 buildx-image
